apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImRtbHNZWGxwYkdGeWRXNDZRWEpBTVRRd05URTVPVEk9IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: myregistrykey
type: kubernetes.io/dockerconfigjson